### ISSUE TITLE
Add Diagram to Visualise the Stack

### ISSUE THREAD

**Issue by nelsonic** [dwyl/technology-stack#1]
Google Doc: https://docs.google.com/drawings/d/1XQooKLpXB-i3gi_svlhSRDbJTlmz352goJvXHreiefg/edit

![dwyl-stack](https://cloud.githubusercontent.com/assets/194400/9353155/378fa35a-465e-11e5-8383-c72368c646ef.jpg)

**Comment by nelsonic** [comment]
![dwyl-stack 1](https://cloud.githubusercontent.com/assets/194400/9354132/ca3aa860-4665-11e5-928c-c69b3c8d26d2.jpg)

**Comment by nelsonic** [comment]
![dwyl-stack 2](https://cloud.githubusercontent.com/assets/194400/9354261/e971fe58-4666-11e5-848f-67dc11d41bfb.jpg)

**Comment by iteles** [comment]
:+1: :blush:

**Comment by nelsonic** [comment]
![dwyl-stack-with-postgres](https://cloud.githubusercontent.com/assets/194400/18927934/e5a9d0a4-85b5-11e6-9c59-4d5052d09053.png)

**Comment by nelsonic** [comment]
Totes updated to PETE:
![dwyl-pete-stack](https://cloud.githubusercontent.com/assets/194400/23000022/7e7c9c88-f3d6-11e6-952a-6d394c0b53f1.png)

**Comment by nelsonic** [comment]
Got a reply in: https://github.com/dwyl/learn-tachyons/issues/5#issuecomment-280175671
So updated to:
![dwyl-pete-stack](https://cloud.githubusercontent.com/assets/194400/23000461/8688abcc-f3d8-11e6-86ab-804720619d8e.png)

**Comment by nelsonic** [comment]
New Stack:
![image](https://cloud.githubusercontent.com/assets/194400/23012325/90b683ea-f41d-11e6-9b14-67beb06cad22.png)

**Comment by nelsonic** [comment]
Closing as I'm satisfied the original requirement has been met. ✅ 
If we need to edit the diagram we can re-open this issue.

**Comment by nelsonic** [comment]
GOTO: #67

**Comment by nelsonic** [comment]
2022: `PETAL` #87 
![dwyl-technology-stack-diagram-PETAL](https://user-images.githubusercontent.com/194400/184719877-a6112c04-7cd9-441f-a293-e6b133d4b67c.png)

https://docs.google.com/drawings/d/12IpbIHRDL0dXXf3pWUo6YWh0lGQ7y-YmQ1Slk4GqIeo/edit

**Comment by nelsonic** [comment]
Sadly, gotta update this diagram to include in Pitch/Proposal ... #171

**Comment by nelsonic** [comment]
# 2026 Update:

<img src="https://github.com/user-attachments/assets/8e0d17f7-9a4d-4e3d-a269-06965aeea8eb" />

**Comment by nelsonic** [comment]
Proooompt for this Mobile First "devices": 

```md
Generate an 4k high resolution 2D image similar to the following:
https://public-images.interaction-design.org/tags/article-what-is-mobile-first-cover.png

Featuring of a set of EXACTLY 5 devices lined up in a row viewed from the front: 
1: Latest Android Google Pixel 10 Pro Device - black
2: Latest iPhone 17 Pro - silver
3: Latest iPad 11-inch in landscape mode - silver
4: Latest MacBook Air 13-inch - silver
5: Latest iMac - silver

The proportional size of the devices should reflect their relative size.

All device screens should feature the SAME modern colourful FULL-SCREEN Todo List App with the title “Today”.
The todo list items should be realistic text a busy professional parent would have on their list no placeholders.
The todo list items must be the SAME text on all devices.

Scale up the App View depending on the size following mobile-first design principles.
The App color scheme should follow the FlatUI Colors: https://flatuicolors.com/palette/defo

The background color behind the devices must be white. No Noise.
Keep the colours of the devices consistent. No shadows.
No device labels below the devices.

All Text must be crisp high resolution.
```

Went through a million iterations and could probably have just created the image myself.
But it's "good enough" if you don't pixel-peep.
And if I ever have time to update it, I will recreate it from scratch.
