### ISSUE TITLE
Wizard Stack?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/technology-stack#12]
@rjmk we _briefly_ discussed this yesterday. Would you mind listing a few of the options?
The main criteria are:
- shallow learning curve for _complete_ beginners - easy to write & debug
- standards-based
- potential for logical separation of components
- isomorphism 
- fast server-side rendering
- minimal front-end footprint (no _massive_ `bundle.js`...)

**Comment by rjmk** [comment]
Hey, @nelsonic! Thanks for wondering about my thoughts! I'll say a couple of things, but certainly take them with a grain of salt! Also, I'm going to say lots of obvious things, but I think it's helpful to say obvious things sometimes.

The first thing is that I can't really say 'one stack is the right stack'. Different technologies and different combinations of technology are suited for different problems. Judging by your requirements, you are focusing on a narrower problem space than 'all web development', but exactly which tools are best for a given job are still likely to vary depending on specifics (I know you know all this, but worth the disclaimer ;) ).

Of course, the other side is that you can't always spare the research / upskilling time to choose and work in the definite best combination of technologies for a given problem, so definitely having some ideas about useful tech is worthwhile.

Though the question is about a stack, your requirements are mostly about frontend, so I'll focus on that.

**[React]** is obviously the elephant in the room. And I definitely see your concerns with its elephantine size. With that compromise comes an amazing amount of community and library support. It also enjoys incredibly widespread usage -- something that gives me more confidence in correct behaviour than any test suite.

I imagine React is not the correct fit for dwyl. Good libraries are less important to an org that eschews external dependencies as much as possible and it's definitely too big for what you're looking for. I think it would be wrong not to start your search for something React-like though. Trying to keep all of the templating logic on the backend requires a lot of discipline and I've not seen a codebase where it's really been done (though this means that may well be a blind spot for me). Doing front end not in terms of views from a state always seems to lead to horror & spaghetti.

So what other alternatives are there to React? Brief honourable mention to **[Elm]**, which I think fulfils all of your requirements well, except for the size of the footprint (and possibly 'isomorphism' / server-side rendering). They are doing some work on improving bundle size, so probably worth keeping an eye on.

The most obvious alternative to React is **[virtual-dom]**. It's a reimplementation of the core concept behind React. One could have a look at how it's used with other modules in **[Mercury]**. A subset of the modules used in Mercury could be right for dwyl's needs.

An aside on notation: this library has a different API to JSX. It's totally possible to use JSX with them. I personally don't like it. I might use something like [hyperscript-helpers] \(destructuring not necessary).

A different set of approaches to virtual dom implementation, but with a similar API and clarity and performance benefits, are those based on [morphdom]. It has the advantage of having a single source of truth (the actual DOM) and the possible disadvantage that I think it will be slightly more difficult to reason about than a virtual dom.

Places to look for using morphdom are **[yo-yo]** and **[choo]**. Choo has a [great summary of the front-end scene][choo-rant]. Both in general contain great information for deciding between these sorts of decisions.

Sorry I didn't do any deep dives, but hopefully this is useful 👍 .

[react]: https://facebook.github.io/react/
[elm]: http://elm-lang.org/
[virtual-dom]: https://github.com/Matt-Esch/virtual-dom
[mercury]: https://github.com/Raynos/mercury
[hyperscript-helpers]: https://github.com/ohanhi/hyperscript-helpers
[morphdom]: https://github.com/patrick-steele-idem/morphdom
[yo-yo]: https://github.com/maxogden/yo-yo
[choo]: https://github.com/yoshuawuyts/choo
[choo-rant]: https://github.com/yoshuawuyts/choo#how-does-choo-compare-to-x

**Comment by rjmk** [comment]
Oh, also I forgot to mention!

> potential for logical separation of components

I'm pretty suspicious of components! I think they often lead to decompositions of the problem that are actually inherently very coupled to each other and just lead to more confusion. I think a must for any frontend solution is allowing normal functions to produce their DOM representations / general widgets. Always thinking in terms of `props`, for example, does not seem to reliably lead to decoupled code (it can be done of course, but I think an important part of beginner friendliness is helping beginners make the right choices)

**Comment by nelsonic** [comment]
@rjmk thanks a _million_ for replying! Hope life at The Guardian is going well. 
we will re-visit/re-open this in the future if/when required. ❤️
