### ISSUE TITLE
GitHub Action to Prevent & Fix Typos!

### ISSUE THREAD

**Issue by nelsonic** [dwyl/technology-stack#120]
As part of my Supabase Deep Dive: https://github.com/dwyl/technology-stack/issues/93#issuecomment-1407304157
I noticed the following file in the root of the repo: https://github.com/supabase/supabase/blob/master/.misspell-fixer.ignore

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/194400/215250008-5c8cecb8-0072-4cec-ab34-45548c07ab50.png">

The file has _one_ line: ignore the https://github.com/supabase/supabase/tree/master/i18n directory.

@stavares843 added via: https://github.com/supabase/supabase/pull/9598
<img width="1462" alt="image" src="https://user-images.githubusercontent.com/194400/215250215-6ab6f05f-b776-44b1-ab2a-10eec2af7db9.png">

And this is the first time the Bot spotted a Typo and _fixed_ it: https://github.com/supabase/supabase/pull/9916
<img width="1960" alt="image" src="https://user-images.githubusercontent.com/194400/215250281-6ba0dcc5-8b6e-4756-bd90-bfd261d23f2c.png">

It was superseded by a PR created by a _human_: https://github.com/supabase/supabase/pull/10043
But hopefully you get the idea! Typos are caught - at least in theory - by CI and fixed by bot! 🤖 

# Todo

+ [ ] Add this to our `MVP` repo: https://github.com/dwyl/mvp and see what it finds. 💭 

@LuchoTurtle do you mind picking this up? 🙏

**Comment by stavares843** [comment]
added a PR [here](https://github.com/dwyl/mvp/pull/286) 🔨
