### ISSUE TITLE
chore: Fresh installing Windows 10 on ThinkPad's laptop

### ISSUE THREAD

**Issue by LuchoTurtle** [dwyl/technology-stack#133]
@dwyl has a neat Lenovo ThinkPad's laptop that is dual-partitioned with Ubuntu and Windows 11. 
However, it seems that Ubuntu's partition is corrupted. I can't seem to log in, as the computer hangs and crashes when trying to boot up and log in with the only user.

![IMG_20230727_141014.jpg](https://github.com/dwyl/technology-stack/assets/17494745/5e8e6d3c-1d14-48b9-91c8-2cae31530f58)

I'm just going to fresh install Windows 10 and format the PC, so it's working in tip-top shape again 👌 

I'll do it later today when I'm back home.

**Comment by LuchoTurtle** [comment]
https://www.microsoft.com/en-gb/software-download/windows10

Going to get the ISO on a flash drive from my PC at home (it's a legit version) so I can install it on ThinkPad.

**Comment by LuchoTurtle** [comment]
![image](https://github.com/dwyl/technology-stack/assets/17494745/0af253dd-6463-4139-a478-22a584671ad0)

While this creates the image on the USB flash, Imma delete the Ubuntu partition.

**Comment by LuchoTurtle** [comment]
![image](https://github.com/dwyl/technology-stack/assets/17494745/4ed9660f-77cb-42a1-a58c-94022e12bebc)

Off it goes.

**Comment by LuchoTurtle** [comment]
![image](https://github.com/dwyl/technology-stack/assets/17494745/94d824ac-05cc-4210-b780-857858bd5d74)

Deleted. Going to use the whole drive for windows now.

**Comment by LuchoTurtle** [comment]
![IMG_20230727_185744.jpg](https://github.com/dwyl/technology-stack/assets/17494745/4a23aae1-cd0c-40bf-9f8d-c9a623a5d732)

Gonna format the Notepad and install Windows 10 now 👌

**Comment by LuchoTurtle** [comment]
![image](https://github.com/dwyl/technology-stack/assets/17494745/4af90875-7c8f-4cb8-bc9f-c7a721503451)

Deleted all partitions. All ready to set up for installing Windows.

![image](https://github.com/dwyl/technology-stack/assets/17494745/6ec1f75b-6ebb-4c9a-ae12-7249166fd0aa)


ref: https://www.groovypost.com/howto/clean-install-Windows-10/

**Comment by LuchoTurtle** [comment]
Now we wait...

![image](https://github.com/dwyl/technology-stack/assets/17494745/dfc11474-d63c-4c57-bd56-8fe9c044eab6)

**Comment by LuchoTurtle** [comment]
We're done 👌👌

![IMG_20230727_191313.jpg](https://github.com/dwyl/technology-stack/assets/17494745/061ba913-6527-4053-8f10-3d27e8b38a8e)

**Comment by iteles** [comment]
This was actually super useful as it seemed like a bit of a long task originally and now I can see it's actually super easy 👌🏻

Thanks for this 😉
