### ISSUE TITLE
Why can't we "just use firebase"...?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/technology-stack#16]
Because of the EU **Data Protection Directive** _**Personal Data**_ of EU citizens should not be transmitted outside of the EU... read: https://en.wikipedia.org/wiki/Data_Protection_Directive#Transfer_of_personal_data_to_third_countries

It is not a "_priority_" for Firebase to launch EU-based servers, see:
https://groups.google.com/forum/#!topic/firebase-talk/7JZ5XWEpUqU

So, _unless_ your app has **_Zero_ Personally Identifiable Information** (**PII**), 
**_or**_ you get people's _consent_ to storing their info on US Servers (_e.g. in Terms & Conditions_)
**_or**_ you _split_ out the data in your app that is Personally Identifiablye vs. non-personal (_and store the PII in EU and the rest in Firebase..._)
You _cannot **legally** use Firebase for an app used by EU Citizens.

**Comment by raptortech-js** [comment]
Google is seeking Privacy Shield approval: https://googlepolicyeurope.blogspot.com/2016/07/eu-us-privacy-shield-restoring-faith-in.html
If granted, it seems likely that Firebase would be included. Instructions for knowing if that has happened: https://www.privacyshield.gov/article?id=How-to-Verify-an-Organization-s-Privacy-Shield-Commitments

**Comment by nelsonic** [comment]
closing this issue. I _actively_ follow the Privacy Shield progress and will re-open if/when it happens.

**Comment by debbiev** [comment]
Does this imply that we can't use the email address for auth purposes?

imo, an email address IS PII.

What about other forms of AUTH?

**Comment by nelsonic** [comment]
@debbiev _great_ question! _Should_ we be using Email addresses for Auth....? ❓ 
If I was to "pick" an Auth mechanism it would be "SQRL": https://www.grc.com/sqrl/sqrl.htm
But given the _ubiquity_ of the Email + Password (_and optional 2nd Factor OTP_),
people are _accustomed_ to using their email address. 
In our App we (_one-way_) _hash_ the email address and use the _hash_ as the "UserID" for the person. All PII is stored in an Encrypted-at-Rest Table and never transmitted over an un-encrypted connection. 
Firebase _could_ be an option if we used a _different_ system/DB to store PII. 🤔

**Comment by Yiidiir** [comment]
any updates on this?

**Comment by nelsonic** [comment]
# 2020 Update: 

4 years later Google still does not allow you to run a Firebase Realtime Database outside of the US.
https://firebase.google.com/docs/projects/locations
![image](https://user-images.githubusercontent.com/194400/71449624-5e36ce00-2748-11ea-95e3-9df61bf60239.png)
This means that _all_ application data is sent across the Atlantic Ocean to the **central US data center** regardless of where the client device is based. Not only is this an uncertainty when it comes to data storage location, it's a huge waste of time if all requests need to perform a 100-800ms round-trip (_depending on where the user is based_). People have reported high latency from India and other Asian countries. 
https://stackoverflow.com/questions/39323517/firebase-realtime-database-location

For the purposes of the GDPR, Firebase customers typically act as the "data controller" (GDPR) for any personal data or information about their end-users they provide to Google in connection with their use of Firebase, and Google generally operates as a "data processor" (GDPR).
https://firebase.google.com/support/privacy#data_protection
![image](https://user-images.githubusercontent.com/194400/71449594-c0db9a00-2747-11ea-81db-a60ba6d63538.png)
This makes sense given that they are merely a service provider; the responsibility for data still belongs to the company/developer _using_ Firebase. The problem is that Firebase does not make it _easy_ for a developer to protect personal data. Data could be encrypted on the client before sending it to Firebase, but how many Apps/devs do this? How many devs even _think_ to encrypt data in their Node.js/Python/etc. Apps `before` storing it?

Google has the following information for the [Privacy Shield Framework](https://www.privacyshield.gov/)
https://cloud.google.com/security/compliance/privacy-shield 
![image](https://user-images.githubusercontent.com/194400/71470188-3f295200-27c3-11ea-8fed-ca1c60c0e7b3.png)

It just reiterates what is on the _official_ Privacy Shield wesbsite:  https://www.privacyshield.gov
![image](https://user-images.githubusercontent.com/194400/71447649-fd4bcd80-2728-11ea-8d21-5d2361c1c94f.png)

https://www.privacyshield.gov/Program-Overview
![image](https://user-images.githubusercontent.com/194400/71447670-5a478380-2729-11ea-998b-2f84201b494e.png)

The purpose of the Privacy Shield Program is to allow _American_ companies to transfer and store the data of EU/Swiss customers. The purpose is _not_ to _fully_ comply with EU [GDPR](https://github.com/dwyl/learn-security#gdpr). In fact several privacy advocacy groups have noted that the "Shield Program" is designed to shield US companies and not the privacy of users. See: https://en.wikipedia.org/wiki/EU%E2%80%93US_Privacy_Shield#Controversy


Firebase _specific_ data processing terms: https://firebase.google.com/terms/data-processing-terms
There is no mention of how data is stored. _Specifically_ there is no mention of it being _encrypted_ at rest.
If Firebase _was_ providing at-rest encryption and allowing the application to control the encryption keys, they would state this prominently as a feature. They aren't encrypting data at _rest_. There is _nothing_ preventing a rogue employee/contractor from reading personal data. (_not saying this will happen, just that it can_) 

![image](https://user-images.githubusercontent.com/194400/71447864-10ac6800-272c-11ea-8055-6f0ee482a65f.png)

Insufficiently protecting people's personal data has the potential for _serious_ fines. 
https://en.wikipedia.org/wiki/GDPR_fines_and_notices
Notice that "***Insufficient protection of personal data***" is a common theme in the companies/organisations being fined. Firebase offers _no_ tools to help developers protect personal data. 

If someone were able to run arbitrary code on your Mobile/Web app with a Firebase backend, they could extract _all_ of the customer/personal data from your Firebase store. Obviously this won't happen during MVP because nobody has _heard_ of your App but later when your app is modestly successful and some [skid](https://en.wikipedia.org/wiki/Script_kiddie) finds your app and targets it, count on having a bad day. 😢 

I'm going to continue giving Firebase a miss even though the features are compelling.
For a _little_ more work I can build a Phoenix App with very similar functionality (_in most cases much faster!_) and be _sure_ that I'm encrypting all personal data and storing it securely.

Further reading:

+ Reddit thread: https://www.reddit.com/r/gdpr/comments/apx6dq/gdpr_compliance_for_firebase_apps
+ Is Google mining Firebase customer data? https://www.quora.com/Is-Google-data-mining-their-clients-Firebase-databases-for-potential-commercial-gains Answer: No. While the answer in this Quora post makes _sense_ from a commercial perspective; Google Cloud Platform has an interest in preserving trust. It does _not_ provide any _evidence_ that special precautions have been taken to protect personal data from a rogue employee/contractor. Specifically regarding how/where data is _stored_. Google the _company_ might not be viewing your personal data, but there is no protection that a DBA could extract/leak it.

**Comment by Yiidiir** [comment]
@nelsonic Maybe they want to people to use Firestore as it's the "upgrade" from Realtime Database, Firestore offers EU locations: https://firebase.google.com/docs/firestore/locations

**Comment by nelsonic** [comment]
@Yiidiir indeed https://firebase.google.com/docs/firestore does allow selection of region and it appears to be a more scalable solution than RTDB. 👍 

In our case we are using Presence to know "who's online" (_so that people can see which team member is available/busy_) in our App. Firestore does not support Presence:
![image](https://user-images.githubusercontent.com/194400/81901956-41941900-95b7-11ea-9946-984a3bd4f381.png)
So we would either need to write some custom logic to work around this or implement a _separate_ Presence mechanism. Phoenix/Elixir gives us Presence for "free" out of the box.

**Comment by nilsreichardt** [comment]
![image](https://user-images.githubusercontent.com/24459435/112465672-46903000-8d65-11eb-9cd6-73d692117a5e.png)

Firebase RTDB is now available outside the US: https://firebase.google.com/docs/projects/locations#rtdb-locations
