### ISSUE TITLE
End of sprint review -> Learnings from working with this stack

### ISSUE THREAD

**Issue by mk4111** [dwyl/technology-stack#22]
(a) Handlebars --> The decision to use this stack was a really good opportunity to step out of the React-hype mindframe. It made me think more about why this app could/should be served from the back-end, what the benefits of using front-end JS were, and how front-end functionality could be achieved without front-end JS.

(b) Redis --> Used the list data-type for the first time and felt like I learned to think about structuring data in formats beyond the obvious --> e.g. considering saving data as stringified objects in lists as opposed to hashes or strings with fieldnames that allowed search by regex.

(c) Tape --> It was really good to find out _what it was that we needed to be testing for_ --> i.e. what the client would be expecting.

I found (what I thought) were two _relatively good_ ways that I could write tests: (1) by writing a _block_ of tests, for a specific feature, for different users/permissions. Then to order them in a way that mimicked the userflow (database would build on the data injected/editted in the previous tests). (2) by writing the tests to follow a userflow (- this made sense, but it meant that our tests were ridiculously long). 

As the project got bigger, I found that depending on the way that the tape tests were written - e.g. chained, not-modular, without the use of promises - they became difficult to maintain and read. For this reason, whilst it seems like quite an obvious point, I feel like the best way to writing tape tests was to write a _block_ of tests per feature, where each script injection tested the same thing, but for a user with different permissions. 

As my focus did shift towards writing tests _so that we would achieve 100% coverage_, I realised that I fell into a false sense of security - that the feature was bug-free. This meant that I became blind to the lack of 'checks' that still needed to be implemented. Although 100% coverage and all tests passing is a step closer to a bug-free app, I realised how important it was to remember that it only tested the things you've _asked_ it to test; if there are things that haven't been considered, then tests for those do not exist --> i.e. your app is _not_ air tight.

(d) ~~ES6~~ --> Although I knew that ES6 wasn't compatible across all browsers, I never really considered that this might _actually_ be a problem for some people. (I also came to realise the application of this same thought to client-heavy apps). It was a really great opportunity to realise which of the methods that I'd been so used to using could easily render the app entirely useless too.

**Comment by nelsonic** [comment]
Great insight @mk4111 ❤️

**Comment by mk4111** [comment]
Thank _you_ @nelsonic :)
