### ISSUE TITLE
Should we investigate using Go + GopherJS for Full-Stack-Go ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/technology-stack#28]
With https://github.com/gopherjs/gopherjs compiling Go to JS is an `<option>` ... 
The "_Benchmarks_" look _good_ and we can (_probably_) all agree that Go is a "_nicer_" language with fewer "_features_" than JS.

> # who has time/inclination _investigate_?

@tonydaly you are the person I know with the most "_production_" Go XP ... _thoughts_?

**Comment by tonydaly** [comment]
I'm generally not a fan of cross language compilers. There's always succinct differences between languages that can cause a whole host of debugging issues.

That said `Go` is a pretty good language and I've found it very productive when writing small APIs (gRPC based microservices). There isn't as much "nice" tooling that you get in JS and Ruby, but the performance benefits might be worthwhile (if that's your bottleneck).

**Comment by nelsonic** [comment]
https://www.quora.com/Why-wasnt-Go-written-as-a-functional-language

**Comment by nelsonic** [comment]
Erlang vs. Go for cuncurrency https://youtu.be/2yiKUIDFc2I

**Comment by nelsonic** [comment]
We've settled on "PETE" for this "_phase_" of @dwyl ✅ 
If anyone want's to explore Go and report back we'd be delighted to hear your findings! 👍 
Closing to de-clutter the issue list.
