### ISSUE TITLE
Which Date Picker ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/technology-stack#30]
@jackcarlisle suggested using: https://github.com/chmln/flatpickr

has anyone else come across an alternative?
what was the _**criteria**_ used to _select_ the picker? 

> relates to: #18

**Comment by iteles** [comment]
@naazy This one was made for you :arrow_up:

**Comment by naazy** [comment]
😄 I like pikaday https://github.com/dbushell/Pikaday- no need for jquery and pretty easy to use

**Comment by jackcarlisle** [comment]
@nelsonic @naazy the reason I chose https://github.com/chmln/flatpickr was because it supports the option for selecting a specific time during the day as well as a date because we're using it with a countdown timer that needs a date and time that is specific to the minute

**Comment by nelsonic** [comment]
@jackcarlisle / @naazy where do you think we should _capture_ the choice of date picker "_tool_"?

**Comment by nelsonic** [comment]
has anyone used: https://github.com/elm-community/elm-datepicker ?
(_the examples look good_)

**Comment by nelsonic** [comment]
_This_ one: https://github.com/dwyl/elm-datepicker
