### ISSUE TITLE
NPM Packages

### ISSUE THREAD

**Issue by ronanyeah** [dwyl/technology-stack#36]
Where are DWYL NPM packages listed?

**Comment by nelsonic** [comment]
@ronanyeah great question! 😍 
we should _really_ get an Org on NPM so all our _useful_ NPM packages are grouped... 👍

**Comment by iteles** [comment]
@ronanyeah YES. Good question and great idea, let's get on this 👍

**Comment by nelsonic** [comment]
We would _love_ to have all our NPM packages organised under the `@dwyl` namespace but NPM were not very helpful on this ... https://github.com/dwyl/hq/issues/568
