### ISSUE TITLE
"New Stack" |> Elixir, Phoenix, Elm & Tachyons?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/technology-stack#37]
![image](https://cloud.githubusercontent.com/assets/194400/22187184/a3572090-e0f9-11e6-8358-562dd0d356a4.png)

The New Stack for 2017 is:

+ Elixir https://github.com/dwyl/learn-elixir
+ Phoenix https://github.com/dwyl/learn-phoenix-framework
  + with PostgreSQL https://github.com/dwyl/learn-postgresql
+ Elm https://github.com/dwyl/learn-elm
+ Tachyons https://github.com/dwyl/learn-tachyons

see: #27

**Comment by jruts** [comment]
Not sure if you want to take advantage of it, but you can call this stack 'PETE'.
Night even be worth it to dedicate a new repo describing the *PETE* stack and why/how to use it, maybe even with some installation scripts/guides to start with the barebones Pete stack.

Any thoughts?

**Comment by des-des** [comment]
@nelsonic do dwly have any projects that have tried out this (awesome) new stack

**Comment by jackcarlisle** [comment]
@des-des https://github.com/healthlocker/healthlocker

**Comment by nelsonic** [comment]
Ok, it's dawned on me that having our "Tech Stack" doc saying one thing and _using_ "New Stack" in _projects_ is sending mixed messages ... so I'm prioritising communicating this better for _today_! 👍

**Comment by nelsonic** [comment]
![Steve Jobs introduces iphone](https://cloud.githubusercontent.com/assets/194400/22934275/4bc76090-f2c6-11e6-9b90-91226e39ea09.png)
Can you guess where the analogy is going...? 😉

**Comment by nelsonic** [comment]
![no-javascript](https://cloud.githubusercontent.com/assets/194400/22939705/88d3e524-f2d7-11e6-91c6-47513f6b4fa7.jpg)
😮  

![image](https://cloud.githubusercontent.com/assets/194400/22939768/ace6b69e-f2d7-11e6-9d87-69ebe71fd3a5.png)

from: https://www.wired.com/2015/11/i-turned-off-javascript-for-a-whole-week-and-it-was-glorious/

**Comment by nelsonic** [comment]
![oops](https://cloud.githubusercontent.com/assets/194400/22981555/9a44e1c4-f394-11e6-85fb-1fff9e88e9e4.png)

We all make "_mistakes_" ... mine was not _embracing_ Elixir earlier!

**Comment by nelsonic** [comment]
@jruts I _really_ like the _succinctness_ of "**PETE**" as a name ...
but I've been racking my brains to think of an _evolution_ of "**PETE**" 
because it sounds like a ["_boy's name_"](http://www.sheknows.com/baby-names/name/pete) 
and we want to be as _inclusive_ as possible ... 
How can we _assemble_ the various letters of the components of our stack into a word.
+ Phoenix
+ Elixir
+ Tachyons
+ Elm

also we are using:
+ Postgres
+ Linux
+ Erlang

and _optionally_:

+ Blockchain
+ProgressiveWebApps
+ Redis
+ MobileFirst
+ OfflineFirst
+ WebRTC

**Comment by nelsonic** [comment]
What about "**TEPPE**" (_which is **sadly not** a gender-neutral **peson's name** which would be **amaze**!_)
But it means "carpet" in Norwegian: https://en.wiktionary.org/wiki/teppe
and means we could have a "***Magic Carpet***" in the Logo!! 😮  😜 
![image](https://cloud.githubusercontent.com/assets/194400/23001168/c48100f2-f3db-11e6-8939-2a5d9122d8bf.png)

**Comment by jruts** [comment]
I kinda like it... Especially with the **Magic Carpet** reference.
It feels like... a whole new world.
A new fantastic point of view.
No one to tell us no or where to go.
Or say we're only dreaming...

**Comment by pdavidow** [comment]
Swap out Tachyons for https://github.com/mdgriffith/style-elements

**Comment by nelsonic** [comment]
@pdavidow we've added Style Elements to our "to learn" list: 
https://github.com/dwyl/learn-elm/issues/96
Our reasoning for using Tachyons is that _several_ of our apps are still Server-Side Rendered.
Style Elements _appears_ to be Elm (_Client-Side_) Focussed.
That's not to say that we won't be experimenting with it and _possibly_ adopting it. 😉
