### ISSUE TITLE
How to avoid "Not Invented Here" ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/technology-stack#38]
Most technology-based organisations/companies suffer from https://en.wikipedia.org/wiki/Not_invented_here _syndrome_...
How do we avoid it?
![image](https://cloud.githubusercontent.com/assets/194400/22198398/4a0c16a8-e14e-11e6-82d4-134b0b78b006.png)

https://www.google.com/search?q=not+invented+here&tbm=isch

relates to #18

**Comment by shouston3** [comment]
I really can't think of good ways to avoid this other than making everyone aware that it is a typical problem in technology companies.

@nelsonic has this been a stumbling block in the past or are you concerned for it happening in the future?

**Comment by nelsonic** [comment]
@shouston3 thanks for replying. This has been a problem in _every_ company I have worked in.
To the extent that the problem has been parodied by several cartoonists and there's even a comic that has the expression as its' name: http://notinventedhe.re/on/2009-9-22 ...
***all*** organisations have this problem. it's a _social_ problem.
Think about it in the context of sports. People support a team that is _clearly_ worse for no reason other than "_it's my team_"... not naming any names (_cough! Nottingham Forrest...!_) 🤣 

the _only_ way we _avoid_ it is by having **_open_ conversations** about other _potential_ technologies where the facts vs. hype, assumptions vs needs, cost vs. benefit are _clearly_ laid out by the person/people making the proposal to use something _different_ from what the team is _already/currently_ using...

We need to follow a _process_ for suggesting new technologies/tools/practices to ensure that we don't have a deluge of "_have you tried XYZ latest framework, can we re-write everything again...?_"

I've gone through several programming languages, frameworks and "_styles_" and have found flaws in each of them. Count yourself _lucky_ that you aren't learning/coding in the "_dark ages_" `before` Git/GitHub, Testing and single-command deployment... 😉 
I'm not one of those "_old timers_" (_which is mid-thirties in our industry_) who is nostalgic about the  "_good old days_"... 

> "_back in my day we didn't need a Virtual DOM SPA with Isomorphic Fetch, to build a website, it was just plain'ol HTML+CSS and a bit of ASP or PHP..._"

I've ***always*** embraced new tools/technologies because _ultimately_ our ***mission*** (_or "job" if you prefer_) is to make something ***reliable*** that solves the requirements of the end-user in the most sustainable and productive way.

I can go into a whole _history lesson_ but will reserve that for _another_ time.
The `tl;dr` is: we need to 
+ ***encourage*** people to try new things
+ ***document*** all our learning in readmes (_preferably screen recordings when things are promising_!)
+ only bring a **proposal/suggestion** to the rest of the team **once** we have **tried it ourselves** (_don't waste other people's time linking to things you haven't tried and can't articulate the benefits of..._)
+ have "***mini projects***" where we `try` out new things. or re-write something small in a new language to see if we can make an improvement on an _existing_ thing.

the thing to note is: No "End User" ***ever*** asked a developer to use "***XYZ Framework***" for the app.
all the people using your app want is for it to be reliable/fast/error-free/secure and they don't care how you get that done!

We as "***creative technologists***" have the right/obligation to learn new things which will help us to _deliver_ the product/project in a more effective way. 
or for example someone could suggest: if we use "***ABC Language***" we can save 60% on our server costs because it takes advantage of multi-core better or handles more concurrent connections, then that's _worth_ considering because it saves money for ***all*** our projects and any by using that tech (_that saves money_) we can gain a "_competitive advantage_" ...

This _always_ needs to be _weighed up_ against the switching/learning cost of something completely new...

If I can say just one more thing on this is: we need to _eliminate_ the mental barriers to learning new things _personally_ first, then as a team we can be a lot more open-minded. ❤️  ✅  🚀

**Comment by nelsonic** [comment]
@jessitron captured it _way_ more eloquently and succinctly:
![image](https://cloud.githubusercontent.com/assets/194400/22402975/b631c5fa-e601-11e6-99f6-092453deb993.png)
https://twitter.com/jessitron/status/617328825131737088

> Adventures in Elm • Jessica Kerr https://youtu.be/cgXhMc8M4X4 😍 
If you haven't watched it, add it to your "watch later" list now! 👍

**Comment by nelsonic** [comment]
https://github.com/dwyl/hq/issues/566
