### ISSUE TITLE
W3C Validation - Why is it important?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/technology-stack#4]
Can't we just ship with HTML/CSS/JS errors and fix them laters?

**Comment by iteles** [comment]
:laughing:

**Comment by nelsonic** [comment]
Need to check if https://github.com/thomasdavis/w3cjs is still working...

**Comment by nelsonic** [comment]
http://zurb.com/article/1260/we-ve-moved-beyond-code-validators

**Comment by nelsonic** [comment]
Open question on React W3C Validation: http://stackoverflow.com/questions/36650295/w3c-html-validation-for-react-jsx-files (_no answers_...)

**Comment by nelsonic** [comment]
Sadly, a few of the `Phoenix` `LiveView` attributes do not pass w3C validation: https://github.com/dwyl/mvp/issues/129#issuecomment-1214444398  🤦‍♂️ 
Not much we can do about it ... 🤷‍♂️ 
Closing. 😞
