### ISSUE TITLE
Project Wiki's

### ISSUE THREAD

**Issue by shouston3** [dwyl/technology-stack#40]
What are the DWYL thoughts on using [github wiki's](https://help.github.com/articles/about-github-wikis/) for managing project [documentation](https://github.com/TheScienceMuseum/collectionsonline/wiki).

Although they give a great interface for indexing and organising the documentation, it's version control is a little awkward as github doesn't offer any interface for managing a wiki's version control.

Other alternatives could be via `gh-pages` or organised markdown files in a `.wiki` directory.

(Personally I think wiki's are the way to go, but I guess I'm after some clarification on what DWYL's preference is for where to put documentation and why).

**Comment by sohilpandya** [comment]
@shouston3 you must've read our mind because me and @iteles were literally talking about this! 😆 

Personally, I've never used Wiki so can't comment on the pros/cons, but I do find README's more accessible than wiki's when looking at 3rd party repos. 

- It's the first page that you will look at as soon as you enter, and sometimes people forget to link there wiki in the readme which leads to confusion 😕

But I'd love to hear a little more on this too! 👍

**Comment by iteles** [comment]
Thanks for raising this @shouston3, we definitely need to write our thoughts on this up https://github.com/dwyl/contributing/issues/25 :heart:

My experience with readme's vs wikis has led me to quite a hard-line insight into this topic: In almost **every** situation, using a readme is preferable to a wiki. 

This is for a number of reasons (in no particular order):
+ There is no way to link an update to the wiki to a specific issue - you can add a reference to it in the 'message' that accompanies your wiki change but this doesn't show up in the issue and isn't clickable from the wiki history
+ When you create a pull request to update functionality, the documentation for the application should also be updated - it is infinitely harder to confirm this has been done (and correctly) if there is no link between the code and the documentation update (i.e. if they're not packaged up into 1 PR)
+ As @sohilpandya points out, the readme is the first thing you see and it's where people expect the information to be contained
+ Permissioning for editing of wikis is [a little fuzzy](https://help.github.com/articles/changing-access-permissions-for-wikis/) so either *everyone* can edit it at random (without going through any second checks or validation) *or* only collaborators can edit it (which makes it very difficult for people who are not already known to an open source project to edit the documentation with any PRs they make, often leading to neglected docs)
+ I have never seen a non-technical user or Product Owner *find* the wiki without being told about it, whereas documentation in the readme has always appeared to be obvious to them
+ In my experience, wikis are often 'where information goes to die' and if you're putting in the work to write something up, it deserves to be seen and easy to find 👍

**Comment by shouston3** [comment]
Another option that we could try out is [embedding the wiki as a submodule of the main repo](https://coderwall.com/p/bwpwwg/the-wiki-as-submodule-pattern).

It seems to solve some of the above problems and looks like a nice way of doing it.

I'm going to have a [little look into this option over the next few days](https://github.com/shouston3/wiki-submodule-example) and let you know if it's any good.

**Comment by shouston3** [comment]
I'm no longer a fan of wiki's and agree with the above, closing
