### ISSUE TITLE
Basic BEM Library

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/technology-stack#43]
Should we have a basic BEM Library as a starting point for all DWYL projects?

Currently @harrygfox is doing a fantastic job with all the UI/UX and then translating it via CSS (BEM methodology) 

But as we found on the **City** Project, starting from scratch can be a bit difficult and time consuming, if we had a starter pack for CSS which contained all the basic CSS it would have made everyone's lives a lot easier. 

I am not suggesting a whole framework (i.e. bootstrap), just all the basic things that will be required to get started. 

I'm also aware that we want to move to using [tachyons](http://tachyons.io) but a lot of the teams are still using BEM and it'd be a great resource to have too! 

Thoughts @iteles @harrygfox @nelsonic

**Comment by nelsonic** [comment]
@sohilpandya completely agree. especially a resource that our _existing_ BEM-based projects can point to... if you have time after "City" project, please _estimate_ how long it will take to put together a resource similar to what @andrewMacmurray did for https://github.com/dwyl/learn-tachyons 👍

**Comment by iteles** [comment]
:+1: Also speaking to Harry about this!

**Comment by nelsonic** [comment]
@sohilpandya if you have time to create a `learn-bem-css` tutorial with a few paragraphs and some links it would be good.

I still think we'll be Using Tachyons for the _foreseeable future_. 
So please _link_ to the `learn-tachyons` so people are aware we are "transitioning" ...
thanks!

**Comment by nelsonic** [comment]
Closing as no longer relevant. ✅ 
Hope you are well Sohil. 👋
