### ISSUE TITLE
Architecture | Reusable components in *every* project

### ISSUE THREAD

**Issue by iteles** [dwyl/technology-stack#44]
Would this be the right repo to also set out our thoughts on a microservices architecture which should be the base for *all* our projects from now on?

In 2017, **we will not start work on a single project which does not also create either reusable components or learning materials**.

**Comment by nelsonic** [comment]
@iteles sure, I don't think we have _another_ place where we can discuss tech-stack related things ... so, yeah this is a great place to start! 👍

**Comment by nelsonic** [comment]
@iteles I'm _assigning_ this to _myself_ and will write a doc on it in the next couple of days and will assign it for review when ready. 👍

**Comment by nelsonic** [comment]
We have _built_ the reusable components:
+ https://github.com/dwyl/auth
+ https://github.com/dwyl/fields
+ https://github.com/dwyl/useful
+ https://github.com/dwyl/statuses

And used them in our MVP: https://github.com/dwyl/mvp

Closing. ✅
