### ISSUE TITLE
Best Oauth library for elixir

### ISSUE THREAD

**Issue by des-des** [dwyl/technology-stack#51]
I have found 2.

https://github.com/scrogson/oauth2
https://github.com/ueberauth/ueberauth

oauth2 has coverage badge, more contributes + releases.. Will dig in a bit more but thought I would ask @nelsonic if you have a preference?

**Comment by jruts** [comment]
https://github.com/ueberauth has very nice libraries for authentication and authorization. It also has libraries for the popular strategies like twitter, facebook, etc...

**Comment by des-des** [comment]
Ok im going with ueberauth, mostly because I am following along your playwith_phoenix. Thanks for both the response and that example!

**Comment by nelsonic** [comment]
Hey @des-des, hope you're well. 👋 
This issue is a bit old now and you have moved on: https://github.com/des-des/imtala 👍 

For anyone reading this after searching Google, please see: https://github.com/dwyl/auth 🔐
