### ISSUE TITLE
Some formatting issues in the readme

### ISSUE THREAD

**Issue by newswim** [dwyl/technology-stack#54]
Chances are this is to do with Github's new stance on GFM becoming the [standard spec](https://githubengineering.com/a-formal-spec-for-github-markdown/) for markdown files. Here's a screenshot of the some of the no-longer-supported syntax:

<img width="1017" alt="screen shot 2017-06-16 at 5 40 13 pm" src="https://user-images.githubusercontent.com/6667096/27247036-14d96eb6-52bb-11e7-8a23-6aecb2311206.png">

Happy to do a PR, just wanted to post an issue first :-]

**Comment by nelsonic** [comment]
@newswim a fix (PR) would be _very_ much welcome. 👍
