### ISSUE TITLE
What about Flux or Redux approach on front-end ?

### ISSUE THREAD

**Issue by cuongngosa** [dwyl/technology-stack#56]
Can you tell more about which data driven model in front-end ?

**Comment by nelsonic** [comment]
@cuongngosa we use Elm for our Front-end Apps. 
Redux is "inspired" by Elm (_i.e. copied the best ideas from Elm_)
Flux is a _more complicated_ version of Redux that has all but lost it's popularity in the React ecosystem. 
What _specifically_ would you like to know about "data driven" ...?

**Comment by nelsonic** [comment]
Closing due to no reply from OP. 
Anyone else _considering_ Redux/Flux, GOTO: https://github.com/dwyl/learn-elm
