### ISSUE TITLE
Documenting setting up redash (a database dashboard MVP)

### ISSUE THREAD

**Issue by Cleop** [dwyl/technology-stack#57]
I am currently setting up an account and database on [Redash](https://redash.io/) for a client to use as a MVP for a usable dashboard to view their site's postgres data. 

Given that this is the second project that I'm doing this for I wondered whether it might be useful to record this process somewhere for others who may go through the same thing. It may also serve to show how simple this process is, to help inform others who might be considering implementing it in the future. 

@nelsonic - any suggestion as to where might be the best place for this?

**Comment by Cleop** [comment]
# Draft notes:

Redash is a paid for service that provides an online, up to date, queryable dashboard of a project's data. Prices start from $29 a month with a free 30 day trial, which is useful for those who may be using it as a stop-gap or want to test the waters of whether it will truly benefit them.

To set up Redash on your project start by going to redash.io and entering in basic details to create an account (name, email, org name, password). You will be able to create accounts for other users at a later date but this number is capped on the free version, so it may be advisable to set up the account using a project email address if you have one.

Having successfully created an account, next you need to connect your account to a 'data source' ie. your project! To connect your data source you will need to fill out the following page: 

![image](https://user-images.githubusercontent.com/16775804/32285039-09508b56-bf21-11e7-9716-2961edc81ffb.png)

- If your page doesn't look like this to start, ensure your first option 'Type'
 has `PostgreSQL` selected. 
- For the 'Name' value enter a name of your choice
- To fill in the remaining values you need to extract this data from your `DATABASE_URL` config variable found on Heroku (under 'Settings' , 'Reveal Config Vars'). The url is structured in the following way and you must dissect the values for each of these things: 

postgres:// **user** : **password** @ **host** : **port** / **name**

**Comment by nelsonic** [comment]
@Cleop please confirm you have _permissions_ to create a `new` repo in @dwyl org for this. 🤔

**Comment by Cleop** [comment]
Closing this issue as the new repo and an issue referencing this one has been set up now
