### ISSUE TITLE
How should we go about setting up restricted phoenix routes?

### ISSUE THREAD

**Issue by samhstn** [dwyl/technology-stack#60]
When we lay out our `router` and authentication for particular roots, we have, so far, been following how [the phoenix book](https://pragprog.com/book/phoenix/programming-phoenix) builds it's router.

For this we use [`Phoenix.Token`](https://hexdocs.pm/phoenix/Phoenix.Token.html). When a user has been verified, we assign a signed token to the `conn` and grant the user entry to the restricted route.

I don't know if there were any issues with this setup from a security perspective, but I did think that it was quite a lot a code which we would always write each time we set up any kind of auth.
It also felt as though it was simplified for the sake of the book and perhaps was not the way to do this in production.

I also wanted to trust myself with less configuration of auth and so [I went looking for a nice library to use](https://github.com/dwyl/learn-phoenix-framework/issues/93#issue-238656750).

It looks to me that [guardian](https://github.com/ueberauth/guardian) is a popular and maintained library (well at least better maintained than it's competitors).
And I like it from an ease of configuration and semantic readable code point of view (I don't think I know enough to comment on the security of how it all works behind the scenes). The minimal setup also allows me to worry as little as possible about where I could be making mistakes with auth.

I've spent the evening reading up on a bunch of alternatives routes to go down (the discussions [here](https://elixirforum.com/t/guardian-jwt-vs-phoenix-token/853) were very interesting but inconclusive).
I also learned from the discussion that I should read up a lot more on how all this stuff works to better be able to discuss how we should be going about answering the above question.

@nelsonic @Danwhy @SimonLab I'd love to know your thoughts on the question in the issue title.

**Comment by nelsonic** [comment]
We created https://github.com/dwyl/auth and https://github.com/dwyl/auth_plug to simplify this by an order of magnitude. 👌
