### ISSUE TITLE
Elm or PureScript (Replacement for JavaScript) ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/technology-stack#64]
We have been using [**`Elm`**](https://github.com/dwyl/technology-stack/issues/27) for _most_ of our Client & Internal Projects for the past 2 years; it's ***awesome***!
Sadly, _much_ of the [Client] work is _closed source_ [_client's decision, not ours_] 😞 
so we only have a handful of re-usable examples/packages published: https://github.com/dwyl?q=elm

**`PureScript`** has only been used on _one_ [Client] project so far, but has been very fruitful.
The people in the team who have the _most_ experience of **`PureScript`** are @roryc89, @Conorc1000  and @finnhodgkin who have written several thousand lines of production `.purs` ... 🎉 
Luckily these gents have _also_ written tons of `Elm` so they are _uniquely_ positioned to _compare_ the two languages/ecosystems and share their _insights_ with the wider community.

What I would _love_ to know (_and, judging from the popularity of the question on [HN](https://news.ycombinator.com/item?id=13427610), I'm sure **many** other people would be keenly interested_) is: 

Given your experience of _both_ **`Elm`** and **`PureScript`** (_i.e. knowing what you know now_):

1. If you were writing a **_Frontend_-only** App ["_from scratch_"] 
that relies on _many_ Browser/DOM APIs, which language would you chose? 

> _Specifically we are writing a "bare bones" tool that will track ("analytics" and "user action") events in Web Apps, the resulting compiled JS needs to be **bulletproof**, **ultra-low-overhead** (memory), **lightning-quick** (load and run on mobile browsers) and easy to **maintain**. The expected lifetime of the code is **at least 5 years** so we need to **invest up-front** to chose the most effective language/tooling/framework. We expect a "core team" of 1-4 people to write 95% of the code with a few Open Source contributions gradually trickling in; so we can afford to use a "less popular" language if it's worth the time/learning investment._

2.  If you were to start a _brand new_ Backend or "Full Stack" project "_from scratch_" 
  would you use **`Elixir`** + **`Elm`** or **`PureScript`**?

## Note on "Other Options"

We are _open_ to considering a "third" option e.g. [**`asm.js`**](http://asmjs.org), [**`idris`**](https://www.idris-lang.org) or [**`nim`**](https://nim-lang.org/)
Our "**selection criteria**" is (_as stated above, but bullet pointed here_):
+ [ ] Compile-to-JS (_ideally only "The Good Parts" and the **earlier** the JS target, the better, e.g: **`ES3`** for maximum browser compatibility, we litterally need our Frontend app to "**run everywhere**"_)
+ [ ] Static Typing (Type-safety) 
+ [ ] Purely Functional (_ideal_)
+ [ ] Good Garbage Collection (_ideal. the lower the memory footprint, the better!_)
+ [ ] Debugger/Debug-ability (_essential_)
+ [ ] Friendly Error Messages (_mega bonus_)
+ [ ] Ecosystem (_bonus_)

## Relevant Background Reading

+ [ ] What functional (or not) programming language that compiles to JS would you choose and why?
https://www.reddit.com/r/javascript/comments/5urukj/what_functional_or_not_programming_language_that/
+ [ ] Why is Elm more popular than PureScript? (_and does that matter?_) https://www.reddit.com/r/haskell/comments/79i7h9/why_is_elm_more_popular_than_purescript

**Comment by finnhodgkin** [comment]
For front-end only development I definitely still recommend elm. 

There are a few major reasons for this:

- The Elm api is a lot smaller so there's less of an on-boarding cost for new developers.
- Purescript provides a language with lots of freedom and no black-box features. Elm on the other hand is focused purely on it's core target: building error-free, maintainable web applications. Less choice in architecture/frameworks/modules is sometimes a _really_ good thing for productivity.  
- Dev experience. Compile times can be quite large in Purescript. For front-end work I find this way more frustrating than back-end (where the majority of our Purescript is). It's not a dealbreaker but I really like to see UI updates instantly. Trying to match designs when there's any kind of a delay in class name changes, etc, is a real pain. There are probably ways to achieve similar speeds with Purescript but Elm gives you those features out of the box with no configuration.

There was a recent elm uprade (.19) that came with a set of features that on the surface I thought were a little disappointing, but I'm now a couple of weeks into using it and I was _so wrong_! The developer experience has been massively streamlined and it's an absolute joy to work with, especially on large projects.

I would pick Purescript if my project:

- Had a really complicated API that changed frequently - Elm decoders can be a pain to write and keep up to date.
- Had a large Purescript back-end. It's much easier to match types if the language is shared between the browser and the server.
- Involved a lot of components or browser features that have already been 'solved' by the wider javascript or React community. The Purescript foreign function interface is a lot more concise and use-able than ports are in Elm - after a bit of setup you can just _use_ javascript functions in Purescript.
- Had an existing javascript codebase. Purescript can be used for parts or the whole, whereas elm takes a take-it-or-leave-it approach.

**Comment by nelsonic** [comment]
Closing as no longer relevant. 
GOTO: #87
