### ISSUE TITLE
Phoenix LiveView Compatibility ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/technology-stack#68]
Chris McCord (_creator of Phoenix_) recently demoed an "in-development" feature called "***LiveView***":
https://dockyard.com/blog/2018/09/12/liveview-project-at-elixirconf-2018
[![image](https://user-images.githubusercontent.com/194400/48288349-bdae1d80-e463-11e8-81f7-e61eb1cb5f3a.png)](https://youtu.be/Z2DU0qLfPIY)
https://youtu.be/Z2DU0qLfPIY (_seriously, watch it!_)

It has the _potential_ to be _game-changing_ in how Realtime Apps are built! 🚀 
seriously, this will leave MetorJS for _dust_ and make most ReactJS apps obsolete! (cc: @rub1e ... 😉)
_However_ is still very much "pre-alpha" ... ⏳ 

As it comes from Chris, it will almost _certainly_ gain _instant_ adoption in the Elixir/Phoenix Community!
(_beyond the fact the functionality is **incredible**, the "author effect" will play a huge role in traction!_)

# How can we _Use_ it?

_How_ can we _proactively_ support it in our "new stack" #67 so that we can _easily_ build realtime apps without writing _any_ JS code! 😮 

> Note: I'm _aware_ of the limitations (_an internet connection is required for server-side re-rendering_) so it won't be applicable to _all_ of our apps, but it's _perfect_ for building "Auth" (_user registration, login & reset-password_) which requires a connection by definition. Another _awesome_ usecase is "Admin" where seeing data being updated/edited in real-time would be _sick_!

# Question: Does this _Replace_ `autoform`?

On the _surface_ LiveView "overlaps" with [**`autoform`**](https://github.com/dwyl/autoform) which automatically renders forms based on Ecto Schema. _However_ as _epic_ as LiveView looks, we are building **`autoform` _now_** (_not sitting on our hands waiting for LiveView to be "stable" ..._)

https://github.com/chrismccord doesn't have anything resembling "LiveView" in his recent GitHub history ... so it _looks_ like it isn't _available_ yet ... 🙄 

I say we "keep an eye" on this and a soon as LiveView is in a _useble_ state we _investigate_ it.

Related to #67 (_extending PETE for rapid prototyping standards-compliant beautiful apps!_)

**Comment by nelsonic** [comment]
This ElixirForum thread is the best place to "watch" this: 
https://elixirforum.com/t/phoenix-liveview-info/16569

**Comment by SimonLab** [comment]
This looks great! I can see also how it can replace some Elm code.
We could also see how to adapt autoform to be able to use it with LiveView

**Comment by nelsonic** [comment]
@SimonLab I can see us using LiveView for all the "online" code 
and then _enhancing_ our apps (PWAs) with Offline Capability wherever we need it. 
For "Admin" views where being online is _essential_ it's going to be _sweet_! 🍭

**Comment by SimonLab** [comment]
It looks like liveView is doing some progress: 
- https://github.com/josevalim/live_eex
- https://www.twitch.tv/videos/339184323
- https://www.twitch.tv/videos/339194715

**Comment by SimonLab** [comment]
"Phoenix.LiveView: Interactive, Real-Time Apps. No Need to Write JavaScript."
https://dockyard.com/blog/2018/12/12/phoenix-liveview-interactive-real-time-apps-no-need-to-write-javascript

**Comment by nelsonic** [comment]
@SimonLab _exciting_! 🎉 
When this is released it's going to be amaze!

**Comment by nelsonic** [comment]
`GOTO`: https://github.com/dwyl/phoenix-liveview-counter-tutorial
