### ISSUE TITLE
Learn Elm or Elixir First (or Both Simultaneously) ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/technology-stack#69]
In light of the fact that the "PETE" stack having **_Two_ Programming Languages**, 
some people feel "_stuck_" with the question: "_**which one** should I **learn first**_?"

This is a _good_ question and I feel it's worthy of having a _detailed_ discussion to help people understand that there isn't a "right" or "wrong" answer; only the answer that "works" for _you_.

Both `Elm` and `Elixir` are "complete" languages that allow us to build entire apps. 
I would _recommend_ that people get a "taste" for both languages but _depending_ on the type of app you are building, pick one to focus on. For example, I am building an app that relies on "Time" in the browser to display a clock in the browser, therefore Elm is my _only_ option<sup>1</sup>. And that is the same for _all_ Apps that require a "rich" user experience. 

Focus on Elm and build a _rich_ user experience.
If you need to persist data, post a comment below and I will _help_ you get started!

> <sup>1</sup>**Note: Yes**, I know this is going to be possible in "Phoenix LiveView" #68 but until that is released as "Alpha" I _have_ to use a front-end tech for building my client apps. Also, "LiveView" will require server-side re-rendering, I want the app I'm currently building to be an "offline first" PWA.

**Comment by sigu** [comment]
Does elm allow someone to have PWA on the same app?

**Comment by nelsonic** [comment]
@sigu good question. ❓ 
For now, there is no _official_ way of doing server-side rendering with **`Elm`**. 
So any App written in Elm is a client-side _only_ App, i.e. Not a Progressive (Server-side Rendered) and client-side _enhanced_ App. 
This is why we use **`Elixir`** for our Server-side programming language (all our apps are rendered on the server) and then enhanced on the client.
In _some_ cases we build our "backend" as an API and do _all_ rendering on the Client, 
but we _prefer_ to build PWAs because sadly the client (browser) is not 100% consistent.
We _still_ encounter users with Internet Explorer or JavaScript disabled.

**Comment by nelsonic** [comment]
To simplify our stack, we've (reluctantly) removed `Elm` and instead are using `LiveView` as part of `PETAL` #87
