### ISSUE TITLE
Explaining the stack externally

### ISSUE THREAD

**Issue by rub1e** [dwyl/technology-stack#70]
It would be very helpful to have an "approved" blurb to help talking through https://github.com/dwyl/technology-stack/issues/67 with potential clients/partners

More specifically, I'm keen to understand _how to talk to potential clients_ about the **modularity/reusability** concept, and what that would mean about working with dwyl; why they might be interested in this way of working / what **benefits** there are for them; equally _why it might not be the right approach_ for a client in a given situation.

Perhaps this could begin as a **discussion** and then I could distil the ideas into a written blurb?

_Grateful_ for everyone's thoughts.

**Comment by rub1e** [comment]
(P2 as I've got a call with a potential client next week)

**Comment by quickbooktech45** [comment]
it would be really great to get a potential client. you can regulate your flow of transaction with Quickbooks. it supports both the desktop and online version and you can easily transfer your Quickbooks data to online. [Intuit support](url=https://in2it.us/) provides assistance for 24/7 so you can contact them when you have an issue.

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/57287789-2e02c800-70b0-11e9-8097-92779da11430.png)

Wow, this Spam account was registered 20 minutes ago and has already posted this helpful comment ...
![image](https://user-images.githubusercontent.com/194400/57287968-7ae69e80-70b0-11e9-9c84-0408fd020afe.png)

Reported as SPAM:
![report-spam](https://user-images.githubusercontent.com/194400/57287856-470b7900-70b0-11e9-9f1b-b26a2bdfc611.png)
![image](https://user-images.githubusercontent.com/194400/57287842-41ae2e80-70b0-11e9-87e5-42202cf3c6c6.png)

Sad.

**Comment by nelsonic** [comment]
Our tech stack is a _lot_ more focussed in 2022. ✅
