### ISSUE TITLE
Which Continous Integration tool to use?

### ISSUE THREAD

**Issue by SimonLab** [dwyl/technology-stack#73]
We are used to integrate [Travis](https://travis-ci.org/) (see also https://github.com/dwyl/learn-travis) in our workflow for continuous integration. However Github now provides its own continuous integration tool via Github Actions, see https://help.github.com/en/actions/automating-your-workflow-with-github-actions/about-continuous-integration

- [ ] Does it support Elixir and nodejs
- [ ] Does it support caching dependencies
- [ ] Can we see the full build and log
- [ ] Compare Travis and Github continuous integartion tool especially the build time

**Comment by nelsonic** [comment]
@SimonLab as discussed, you've added GitHub CI support to https://github.com/dwyl/elixir-auth-google
e.g: https://github.com/dwyl/elixir-auth-google/runs/321881640 👍 
Were you able to figure out how to add a "Badge" to the `README.md` as a quick visual of pass/fail?

**Comment by SimonLab** [comment]
I manage to find the following badge for elixir-auth-google:
[![Build Status](https://github.com/dwyl/elixir-auth-google/workflows/Elixir%20CI/badge.svg)](https://github.com/dwyl/elixir-auth-google)

link of the image:
https://github.com/dwyl/elixir-auth-google/workflows/Elixir%20CI/badge.svg

**Comment by nelsonic** [comment]
@SimonLab _how_/_where_ did you _find_ that? it does not appear to be navigable via the UI ...
![image](https://user-images.githubusercontent.com/194400/69674640-ce442c80-1094-11ea-8942-5bc92817e90c.png)

A bit of googling lead me to:
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository
But it's not possible to alter the type of badge e.g: `?style=flat-square` ... 😞

**Comment by samhstn** [comment]
@nelsonic @SimonLab what are your thoughts around [Cirrus CI](https://cirrus-ci.org/)?

It's the one [elixir-lang](https://github.com/elixir-lang/elixir) is using and it looks pretty fast.

Elixir forum discussion if you're interested: https://elixirforum.com/t/experience-with-cirrus-ci/21357/12

**Comment by nelsonic** [comment]
Hi @samhstn! 👋 
Had not explored Cirrus* CI ... thanks for bringing it to our attention. Have you tried it on any of your projects?
Looks like Elixir Lang made the switch fairly recently: https://twitter.com/elixirlang/status/1194969021298466816
![image](https://user-images.githubusercontent.com/194400/69682890-d909bc00-10aa-11ea-815b-e7006a47b56f.png)

Is the main advantage that it allows "BYO infrastructure"? The ability to test on multiple OSes is appealing.
Not much else to go on from the home page ... 
![image](https://user-images.githubusercontent.com/194400/69682917-eb83f580-10aa-11ea-913b-af474722b72a.png)

https://cirrus-ci.org/features has a bit more info
![image](https://user-images.githubusercontent.com/194400/69682939-02c2e300-10ab-11ea-989f-b5c0e071d33d.png)

Comparison table: https://cirrus-ci.org/features/#comparison-with-popular-ciaas
![image](https://user-images.githubusercontent.com/194400/69683017-40277080-10ab-11ea-99a1-0fc8707a0eb6.png)
Travis-CI our current "default" CI for all our Open Source projects supports Linux, Mac and Windows
and it hasn't been a "bottleneck" in our dev workflow (_yet_...)

We don't _need_ to support FreeBSD right now, but it might be a consideration in the future.
I've often considered switching to OpenBSD 🤔 
https://en.wikipedia.org/wiki/Comparison_of_BSD_operating_systems#OpenBSD

<hr />

![image](https://user-images.githubusercontent.com/194400/69682673-1883d880-10aa-11ea-8514-5a3af89ee410.png)

*cirrus ... serious ... 🙄

**Comment by nelsonic** [comment]
Thanks to @SimonLab's efforts, we've been using **Github Actions** for our various `Elixir` projects for the past few months. It's been _adequate_. Not saying we wouldn't consider an alternative CI provider if the need arrises.
But given that Elixir-Lang is using it too: https://github.com/elixir-lang/elixir/blob/main/.github/workflows/ci.yml I feel that we're well-served. 

Closing. ✅
