### ISSUE TITLE
Learn-elm npm is not explained

### ISSUE THREAD

**Issue by miguelmartins17** [dwyl/technology-stack#77]
I was reading the learn-elm repository/project and noticed that within this project the term npm is mentioned several times. And I was thinking for people who want to learn elm it would be important to have all the terms or abbreviations properly explained even in notes so that we can leave them more elucidated.
If you think a link can help you about what npm is here: [https://nodejs.org/en/knowledge/getting-started/npm/what-is-npm/](url)

**Comment by nelsonic** [comment]
Thanks again for opening this issue. ❤️ 
`NPM` is no longer relevant to our stack in 2022, so closing. ✅
