### ISSUE TITLE
Learn Python 

### ISSUE THREAD

**Issue by miguelmartins17** [dwyl/technology-stack#78]
How can I start learning python?
We don't have any repository that helps new people learn python.

**Comment by nelsonic** [comment]
@miguelmartins17 we have https://github.com/dwyl/learn-python to capture all notes on learning Python.
A good starting point is: https://github.com/dwyl/learn-python/issues/3

**Comment by miguelmartins17** [comment]
@nelsonic  thanks is I'd like to start learning something about Python.

**Comment by iteles** [comment]
@miguelmartins17 Shall we close this issue now that it's been answered?

**Comment by miguelmartins17** [comment]
@iteles Yes sure

**Comment by nelsonic** [comment]
GOTO: https://github.com/dwyl/learn-python/issues/3
