### ISSUE TITLE
What do you know about "Chocolatey.org"

### ISSUE THREAD

**Issue by miguelmartins17** [dwyl/technology-stack#79]
I was trying to solve an issue and I was doing some research on how I could get dart installed on the command line or powershell and of the few people I saw trying to install dart-sdk on the command line they all say it's necessary to install "Chocolatey" first.
I would like to know if anyone has ever used it or if they know what it's for.

**Comment by nelsonic** [comment]
Included in https://github.com/dwyl/learn-dart#dart-installation ✅
