### ISSUE TITLE
greenkeeper.io is the dependency manager we've been looking for...

### ISSUE THREAD

**Issue by nelsonic** [dwyl/technology-stack#9]
http://greenkeeper.io/

**Comment by iteles** [comment]
:+1: That's pretty cool!

**Comment by nelsonic** [comment]
Not using because it requires Admin access to org and all repos. 😞

**Comment by des-des** [comment]
@nelsonic but some of their source in on gh. https://github.com/semantic-release/semantic-release. It might be possible to host it ourselves.

**Comment by nelsonic** [comment]
@des-des go on... 😉

**Comment by des-des** [comment]
I think probably there is more pain then gain there. But wrapping up that module in a server on aws/heroku which is registered to gh hooks. Then I think we would need a bunch of calls to the gh api to do the pull requests + merging + all the stuff greenkeeper have not open sourced..

**Comment by des-des** [comment]
obvs that server would need all the same permissions but it would be ours..

**Comment by nelsonic** [comment]
yeah, there's quite a bit of "*wiring*" code required... but it would be *superb* to automate the process of updating dependencies ... this is a mini-project worthy of a bounty!

**Comment by nelsonic** [comment]
see: https://github.com/dwyl/hq/issues/100
